// =========================================================
// INC-22 / INC-16f — Operator escalations (§H.3) + vendor batch ticket (§H.4)
//
// Plan v4 §H.3 routes operator escalations through Paperclip child issues —
// NEVER free-form Telegram/Slack. One child issue per (vendor, failure_type,
// tick) batch. So 12 H4-suspended Helix SIMs in a single tick collapse into
// one issue with 12 line items, not 12 issues.
//
// Plan v4 §H.4 vendor-batched ticket (still toggle-gated, default off).
// Trigger: ≥5 SIMs in same vendor account in terminal-suspended/barred state
// in 24h AND per-carrier toggle on (KV `vendor_batch_ticket_<vendor>`='true').
//
// Pure functions for batching, table-driven failure-type catalogue, and a
// thin Paperclip API client.
//
// Identifier surface:
//   - operator-facing → ICCID OK (operators see it in the dashboard).
//   - reseller-facing → never; we never emit reseller-facing messages here.
//   - No secrets in line items.
// =========================================================

// §H.3 — the 14 enumerated failure types + 'generic' fallback.
export const ESCALATION_FAILURE_TYPES = Object.freeze([
  'verify_send_failed',
  'verify_receive_timeout',
  'vendor_active_no_sms',
  'vendor_iccid_not_found',
  'imei_wrong_type',
  'imei_drift_vendor',
  'vendor_cancelled_active_rental',
  'wing_w7_dialable_retry_failed',
  'helix_unsuspend_failed',
  'atomic_restore_failed',
  'teltik_reset_failed',
  'teltik_forward_url_misconfigured',
  'unable_to_reproduce_recommendation',
  'generic',
]);

const FAILURE_TYPE_SET = new Set(ESCALATION_FAILURE_TYPES);

// Coerce a free-form classifier escalation_reason or executor failure to one
// of the enumerated §H.3 failure types. Anything we cannot map falls to
// 'generic' so it still batches predictably.
export function normalizeFailureType(reason) {
  if (!reason) return 'generic';
  const r = String(reason).toLowerCase();
  if (FAILURE_TYPE_SET.has(r)) return r;
  // Common aliases from classifier / verify-runner / executors.
  if (r === 'wing_not_activated' || r === 'w7_failed') return 'wing_w7_dialable_retry_failed';
  if (r.startsWith('helix_unsuspend')) return 'helix_unsuspend_failed';
  if (r.startsWith('atomic_restore')) return 'atomic_restore_failed';
  if (r.startsWith('teltik_reset')) return 'teltik_reset_failed';
  if (r.startsWith('teltik_forward')) return 'teltik_forward_url_misconfigured';
  if (r === 'insufficient_evidence' || r === 'insufficient_evidence_no_vendor'
      || r === 'insufficient_evidence_unknown_vendor') return 'generic';
  return 'generic';
}

// Group a flat list of escalation candidates by (vendor, failure_type).
// Returns Array<{ vendor, failure_type, items: LineItem[] }>.
export function groupEscalations(candidates) {
  const buckets = new Map();
  for (const c of candidates || []) {
    const vendor = String(c.vendor || 'unknown').toLowerCase();
    const failure_type = normalizeFailureType(c.failure_type || c.escalation_reason);
    const key = vendor + '|' + failure_type;
    let bucket = buckets.get(key);
    if (!bucket) {
      bucket = { vendor, failure_type, items: [] };
      buckets.set(key, bucket);
    }
    bucket.items.push(c.line_item);
  }
  return Array.from(buckets.values());
}

// Compute the tick id (2h boundary, ISO of UTC slot start). The remediator
// cron fires at minute 0 of every 2nd hour, so we round 'now' down to the
// nearest even-hour UTC slot to dedup retries that fire mid-tick.
export function computeTickId(now) {
  const d = now instanceof Date ? now : new Date(now);
  const ms = d.getTime();
  const SLOT = 2 * 60 * 60 * 1000;
  const slot = new Date(Math.floor(ms / SLOT) * SLOT);
  return slot.toISOString();
}

// Build the Paperclip issue title + body for a §H.3 batch.
export function buildEscalationIssue({ vendor, failure_type, items, tickId, parentIssueId }) {
  const title = '[auto-remediator] ' + vendor + ' / ' + failure_type
    + ' — ' + items.length + ' rental' + (items.length === 1 ? '' : 's') + ' need operator';

  const lines = [];
  lines.push('Vendor: **' + vendor + '**');
  lines.push('Failure type: `' + failure_type + '`');
  lines.push('Tick: `' + tickId + '`');
  if (parentIssueId) lines.push('Parent: ' + parentIssueId);
  lines.push('');
  lines.push('## Line items');
  lines.push('');
  for (const it of items) {
    lines.push(renderLineItem(it));
    lines.push('');
  }
  lines.push('---');
  lines.push('Auto-generated by `bad-rental-remediator`. Do NOT route via Telegram/Slack.');
  return { title, body: lines.join('\n') };
}

function renderLineItem(it) {
  const parts = [];
  parts.push('### Report ' + it.report_id);
  if (it.reseller_rental_id) parts.push('- reseller_rental_id: `' + it.reseller_rental_id + '`');
  if (it.current_mdn)        parts.push('- current MDN: `' + it.current_mdn + '`');
  if (it.iccid)              parts.push('- ICCID: `' + it.iccid + '`');
  if (it.vendor)             parts.push('- vendor: `' + it.vendor + '`');
  if (it.situation_id)       parts.push('- situation: `' + it.situation_id + '`');
  if (it.attempts && it.attempts.length) {
    parts.push('- attempts:');
    for (const a of it.attempts) {
      parts.push('  - `' + (a.action || '?') + '` → `' + (a.outcome || '?') + '`'
        + (a.vendor_request_id ? '  (vendor_request_id=`' + a.vendor_request_id + '`)' : ''));
    }
  }
  if (it.latest_vendor_state) parts.push('- latest vendor state: `' + safeJson(it.latest_vendor_state) + '`');
  if (it.latest_webhook)      parts.push('- latest webhook: `' + safeJson(it.latest_webhook) + '`');
  if (it.verify_state)        parts.push('- verify: sent=`' + !!it.verify_state.sent + '` received=`' + !!it.verify_state.received + '`');
  if (it.suggested_next)      parts.push('- suggested next: ' + it.suggested_next);
  return parts.join('\n');
}

function safeJson(v) {
  try { return typeof v === 'string' ? v : JSON.stringify(v); } catch { return '<unserializable>'; }
}

// ---------------------------------------------------------
// DB-backed dedup + Paperclip POST.
//
// reserveEscalation: tries to insert one operator_escalations row per
// (tick_id, vendor, failure_type). On UNIQUE violation returns null —
// another tick / retry already claimed this batch.
//
// postEscalation: attempts Paperclip API call; updates the row to
// 'posted' on success, 'post_failed' with last_error on failure.
// Returns { ok, issueId }.
// ---------------------------------------------------------

export async function reserveEscalation(env, batch) {
  const row = {
    tick_id: batch.tick_id,
    vendor: batch.vendor,
    failure_type: batch.failure_type,
    report_ids: batch.report_ids || [],
    line_items: batch.line_items || [],
    paperclip_parent_id: batch.parentIssueId || null,
    status: 'queued',
  };
  const resp = await fetch(env.SUPABASE_URL + '/rest/v1/operator_escalations', {
    method: 'POST',
    headers: {
      apikey: env.SUPABASE_SERVICE_ROLE_KEY,
      Authorization: 'Bearer ' + env.SUPABASE_SERVICE_ROLE_KEY,
      'Content-Type': 'application/json',
      Prefer: 'return=representation',
    },
    body: JSON.stringify(row),
  });
  if (resp.status === 409) return null; // UNIQUE conflict — already reserved.
  if (!resp.ok) {
    const txt = await resp.text();
    throw new Error('reserveEscalation failed ' + resp.status + ' ' + txt);
  }
  const rows = await resp.json().catch(() => []);
  return Array.isArray(rows) && rows[0] || null;
}

export async function postEscalation(env, reservedRow, issuePayload) {
  if (!env.PAPERCLIP_API_URL || !env.PAPERCLIP_API_KEY) {
    await updateEscalationRow(env, reservedRow.id, {
      status: 'queued',
      last_error: 'paperclip_credentials_missing',
      updated_at: new Date().toISOString(),
    });
    return { ok: false, error: 'paperclip_credentials_missing' };
  }
  const reqBody = {
    title: issuePayload.title,
    body: issuePayload.body,
    parent_id: reservedRow.paperclip_parent_id || null,
    labels: ['auto-remediator', reservedRow.vendor, reservedRow.failure_type],
  };
  let httpResp;
  try {
    httpResp = await fetch(env.PAPERCLIP_API_URL.replace(/\/+$/, '') + '/api/issues', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: 'Bearer ' + env.PAPERCLIP_API_KEY,
      },
      body: JSON.stringify(reqBody),
    });
  } catch (err) {
    await updateEscalationRow(env, reservedRow.id, {
      status: 'post_failed',
      last_error: 'paperclip_fetch_error: ' + String(err).slice(0, 200),
      updated_at: new Date().toISOString(),
    });
    return { ok: false, error: 'paperclip_fetch_error' };
  }
  if (!httpResp.ok) {
    const txt = await httpResp.text().catch(() => '');
    await updateEscalationRow(env, reservedRow.id, {
      status: 'post_failed',
      last_error: 'paperclip_http_' + httpResp.status + ': ' + txt.slice(0, 200),
      updated_at: new Date().toISOString(),
    });
    return { ok: false, error: 'paperclip_http_' + httpResp.status };
  }
  const data = await httpResp.json().catch(() => ({}));
  const issueId = data && (data.id || data.issue_id || data.issueId) || null;
  await updateEscalationRow(env, reservedRow.id, {
    status: 'posted',
    paperclip_issue_id: issueId,
    posted_at: new Date().toISOString(),
    last_error: null,
    updated_at: new Date().toISOString(),
  });
  return { ok: true, issueId };
}

async function updateEscalationRow(env, id, patch) {
  return fetch(env.SUPABASE_URL + '/rest/v1/operator_escalations?id=eq.' + encodeURIComponent(id), {
    method: 'PATCH',
    headers: {
      apikey: env.SUPABASE_SERVICE_ROLE_KEY,
      Authorization: 'Bearer ' + env.SUPABASE_SERVICE_ROLE_KEY,
      'Content-Type': 'application/json',
      Prefer: 'return=minimal',
    },
    body: JSON.stringify(patch),
  });
}

// ---------------------------------------------------------
// Tick-level flush. Called once at end of runTick with the candidates the
// per-report processor accumulated. Idempotent across retries within the
// same 2h slot via (tick_id, vendor, failure_type) uniqueness.
// ---------------------------------------------------------

export async function flushEscalations(env, { now = new Date(), candidates, parentIssueId } = {}) {
  if (!candidates || candidates.length === 0) {
    return { batches: 0, posted: 0, reserved: 0, skipped_dedup: 0 };
  }
  const tickId = computeTickId(now);
  const grouped = groupEscalations(candidates);
  let posted = 0, reserved = 0, skipped = 0;
  for (const g of grouped) {
    const row = await reserveEscalation(env, {
      tick_id: tickId,
      vendor: g.vendor,
      failure_type: g.failure_type,
      report_ids: g.items.map(it => it.report_id).filter(Boolean),
      line_items: g.items,
      parentIssueId,
    });
    if (!row) { skipped++; continue; }
    reserved++;
    const issuePayload = buildEscalationIssue({
      vendor: g.vendor,
      failure_type: g.failure_type,
      items: g.items,
      tickId,
      parentIssueId,
    });
    const post = await postEscalation(env, row, issuePayload);
    if (post.ok) posted++;
  }
  return { batches: grouped.length, posted, reserved, skipped_dedup: skipped, tickId };
}

// ---------------------------------------------------------
// §H.4 — vendor-batch ticket (still toggle-gated, default off).
//
// For each vendor with toggle on (KV `vendor_batch_ticket_<vendor>`='true'),
// count distinct sim_ids that have hit terminal-suspended/barred in the last
// 24h. If count ≥ 5 and we have not already opened a vendor-batch ticket
// for this (tick_id, vendor) → open one with vendor-side ICCIDs.
//
// Vendor-side ICCIDs ONLY in body; never reseller-facing identifiers.
// ---------------------------------------------------------

const VENDORS = ['atomic', 'wing_iot', 'helix', 'teltik'];
const VENDOR_BATCH_THRESHOLD = 5;
const VENDOR_BATCH_WINDOW_MS = 24 * 60 * 60 * 1000;

export async function maybeOpenVendorBatchTickets(env, { now = new Date(), parentIssueId } = {}) {
  if (!env.REMEDIATOR_KV) return { vendors: [], opened: 0 };
  const tickId = computeTickId(now);
  const sinceIso = new Date(now.getTime() - VENDOR_BATCH_WINDOW_MS).toISOString();
  const results = [];
  let opened = 0;
  for (const vendor of VENDORS) {
    const toggle = await env.REMEDIATOR_KV.get('vendor_batch_ticket_' + vendor);
    const enabled = toggle === 'true' || toggle === '1';
    if (!enabled) {
      results.push({ vendor, enabled: false });
      continue;
    }
    const iccids = await fetchTerminalSuspendedIccids(env, vendor, sinceIso);
    if (iccids.length < VENDOR_BATCH_THRESHOLD) {
      results.push({ vendor, enabled: true, count: iccids.length, below_threshold: true });
      continue;
    }
    const reserved = await reserveEscalation(env, {
      tick_id: tickId,
      vendor,
      failure_type: 'vendor_batch',
      report_ids: [],
      line_items: iccids.map(iccid => ({ iccid })), // vendor-side only
      parentIssueId,
    });
    if (!reserved) {
      results.push({ vendor, enabled: true, count: iccids.length, skipped_dedup: true });
      continue;
    }
    const issuePayload = buildVendorBatchIssue({ vendor, iccids, tickId, parentIssueId });
    const post = await postEscalation(env, reserved, issuePayload);
    if (post.ok) opened++;
    results.push({ vendor, enabled: true, count: iccids.length, posted: post.ok });
  }
  return { vendors: results, opened, tickId };
}

export function buildVendorBatchIssue({ vendor, iccids, tickId, parentIssueId }) {
  const title = '[vendor-batch] ' + vendor + ' — ' + iccids.length + ' SIMs terminal-suspended in 24h';
  const body = [
    'Vendor: **' + vendor + '**',
    'Window: last 24h',
    'Threshold: ≥' + VENDOR_BATCH_THRESHOLD,
    'Tick: `' + tickId + '`',
    parentIssueId ? 'Parent: ' + parentIssueId : '',
    '',
    '## Vendor-side ICCIDs',
    '',
    iccids.map(i => '- `' + i + '`').join('\n'),
    '',
    '---',
    'Vendor-side identifiers only. NO reseller-facing identifiers in this ticket.',
  ].filter(Boolean).join('\n');
  return { title, body };
}

async function fetchTerminalSuspendedIccids(env, vendor, sinceIso) {
  // Pull sims in terminal-suspended-shaped statuses for this vendor that
  // transitioned recently. We accept the worker DB schema's `sims.status`
  // values: 'suspended','barred','terminal_suspended','permanently_barred'.
  // `deactivated_at` and `last_status_change_at` are the recency signals; we
  // fall back to deactivated_at if the schema lacks last_status_change_at.
  const statuses = ['suspended', 'barred', 'terminal_suspended', 'permanently_barred'];
  const statusFilter = encodeURIComponent('(' + statuses.join(',') + ')');
  const q = 'sims?vendor=eq.' + encodeURIComponent(vendor)
    + '&status=in.' + statusFilter
    + '&deactivated_at=gte.' + encodeURIComponent(sinceIso)
    + '&select=iccid&limit=1000';
  const resp = await fetch(env.SUPABASE_URL + '/rest/v1/' + q, {
    headers: {
      apikey: env.SUPABASE_SERVICE_ROLE_KEY,
      Authorization: 'Bearer ' + env.SUPABASE_SERVICE_ROLE_KEY,
    },
  });
  if (!resp.ok) {
    console.log('[Escalations] vendor-batch query failed for ' + vendor + ': ' + resp.status);
    return [];
  }
  const rows = await resp.json().catch(() => []);
  const seen = new Set();
  const out = [];
  for (const r of (Array.isArray(rows) ? rows : [])) {
    if (r && r.iccid && !seen.has(r.iccid)) {
      seen.add(r.iccid);
      out.push(r.iccid);
    }
  }
  return out;
}
