-- ============================================
-- MIGRATION 003: Add Gateways Table
-- Manages multiple Skyline gateway devices by MAC address
-- ============================================

-- 1. Create gateways table
CREATE TABLE IF NOT EXISTS public.gateways (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mac_address text UNIQUE NOT NULL,
    code text NOT NULL,                    -- Display code like "512-1", "64-1"
    name text,                             -- Friendly name like "Office Gateway"
    location text,                         -- Physical location
    ip_address text,                       -- For reference/management
    total_ports integer DEFAULT 64,        -- Number of SIM ports on this gateway
    notes text,                            -- Any additional notes
    active boolean DEFAULT true,           -- Whether gateway is active
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);

-- 2. Add gateway_id to sims table
ALTER TABLE public.sims
ADD COLUMN IF NOT EXISTS gateway_id bigint REFERENCES public.gateways(id);

-- 3. Create index for faster lookups
CREATE INDEX IF NOT EXISTS idx_gateways_mac_address ON public.gateways(mac_address);
CREATE INDEX IF NOT EXISTS idx_sims_gateway_id ON public.sims(gateway_id);

-- 4. Insert your existing gateway (update MAC and code as needed)
-- Example: INSERT INTO gateways (mac_address, code, name) VALUES ('00-31-f1-02-1a-ff', '64-1', 'Main Gateway');

-- ============================================
-- USAGE NOTES:
--
-- Add a new gateway:
--   INSERT INTO gateways (mac_address, code, name, location)
--   VALUES ('00-31-f1-xx-xx-xx', '512-1', 'New Gateway', 'Office');
--
-- The sms-ingest worker will automatically link SIMs to gateways
-- based on the MAC address in incoming SMS requests.
-- ============================================
