-- ============================================
-- MIGRATION 005: Skyline API Logs + SIM Columns
-- Tracks all SkyLine gateway API calls for debugging
-- Adds IMEI and slot columns to sims table
-- ============================================

-- Skyline API call logging table (mirrors helix_api_logs pattern)
CREATE TABLE IF NOT EXISTS public.skyline_api_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id text NOT NULL,
    action text NOT NULL,
    gateway_id bigint REFERENCES public.gateways(id),
    port text,
    request_url text NOT NULL,
    request_body jsonb,
    response_status integer,
    response_ok boolean,
    response_body jsonb,
    error text,
    created_at timestamptz DEFAULT now()
);

-- Indexes for querying
CREATE INDEX IF NOT EXISTS idx_skyline_api_logs_created_at ON skyline_api_logs(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_skyline_api_logs_gateway_id ON skyline_api_logs(gateway_id);
CREATE INDEX IF NOT EXISTS idx_skyline_api_logs_action ON skyline_api_logs(action);

-- Add IMEI and slot columns to sims table
ALTER TABLE public.sims
ADD COLUMN IF NOT EXISTS imei text,
ADD COLUMN IF NOT EXISTS slot text DEFAULT 'A';
