-- Migration: Wing Bill Verification + SIM Status History
-- Run this in Supabase SQL Editor

-- =====================================================
-- 1. SIM STATUS HISTORY TABLE
-- =====================================================
-- Tracks every status change on the sims table for pro-rated billing

CREATE TABLE IF NOT EXISTS public.sim_status_history (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sim_id bigint REFERENCES public.sims(id) NOT NULL,
    old_status text,
    new_status text NOT NULL,
    changed_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_sim_status_history_sim_id ON public.sim_status_history(sim_id);
CREATE INDEX IF NOT EXISTS idx_sim_status_history_changed_at ON public.sim_status_history(changed_at);

-- =====================================================
-- 2. TRIGGER: auto-log status changes on sims table
-- =====================================================

CREATE OR REPLACE FUNCTION log_sim_status_change() RETURNS trigger AS $$
BEGIN
    IF OLD.status IS DISTINCT FROM NEW.status THEN
        INSERT INTO public.sim_status_history (sim_id, old_status, new_status)
        VALUES (NEW.id, OLD.status, NEW.status);
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_sim_status_change ON public.sims;
CREATE TRIGGER trg_sim_status_change
    AFTER UPDATE OF status ON public.sims
    FOR EACH ROW EXECUTE FUNCTION log_sim_status_change();

-- =====================================================
-- 3. WING BILL UPLOADS TABLE
-- =====================================================

CREATE TABLE IF NOT EXISTS public.wing_bill_uploads (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    filename text,
    billing_period_start date,
    billing_period_end date,
    total_rows integer DEFAULT 0,
    total_amount numeric(10,2) DEFAULT 0,
    total_expected numeric(10,2) DEFAULT 0,
    discrepancy_count integer DEFAULT 0,
    overcharge_amount numeric(10,2) DEFAULT 0,
    status text DEFAULT 'pending' CHECK (status IN ('pending', 'processing', 'complete', 'error')),
    error_message text,
    created_at timestamptz DEFAULT now()
);

-- =====================================================
-- 4. WING BILL LINES TABLE
-- =====================================================

CREATE TABLE IF NOT EXISTS public.wing_bill_lines (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    upload_id bigint REFERENCES public.wing_bill_uploads(id) ON DELETE CASCADE NOT NULL,
    wing_id text,
    item_type text,
    description text,
    from_date timestamptz,
    to_date timestamptz,
    subscription_name text,
    subscription_iccid text,
    subscription_identifier text,
    carrier text,
    price numeric(10,2),
    -- Verification result columns
    sim_id bigint,
    sim_status text,
    expected_price numeric(10,2),
    billable_days integer,
    total_days integer,
    discrepancy_type text,
    discrepancy_detail text,
    created_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_wing_bill_lines_upload_id ON public.wing_bill_lines(upload_id);
CREATE INDEX IF NOT EXISTS idx_wing_bill_lines_iccid ON public.wing_bill_lines(subscription_iccid);
CREATE INDEX IF NOT EXISTS idx_wing_bill_lines_discrepancy ON public.wing_bill_lines(discrepancy_type) WHERE discrepancy_type IS NOT NULL;

-- =====================================================
-- 5. PERMISSIONS
-- =====================================================

GRANT ALL ON ALL TABLES IN SCHEMA public TO postgres, anon, authenticated, service_role;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO postgres, anon, authenticated, service_role;
