-- ============================================
-- COMPLETE SCHEMA FOR TEST ENVIRONMENT
-- Run this in: https://supabase.com/dashboard/project/lwapudjjlwkskijefxdz/sql/new
-- ============================================

-- 1. RESELLERS TABLE
CREATE TABLE IF NOT EXISTS public.resellers (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    created_at timestamp with time zone DEFAULT now()
);

-- 2. RESELLER API KEYS TABLE
CREATE TABLE IF NOT EXISTS public.reseller_api_keys (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reseller_id bigint REFERENCES public.resellers(id),
    api_key text UNIQUE NOT NULL,
    enabled boolean DEFAULT true,
    created_at timestamp with time zone DEFAULT now()
);

-- 3. NUMBERS TABLE
CREATE TABLE IF NOT EXISTS public.numbers (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    e164 text UNIQUE NOT NULL,
    status text DEFAULT 'active',
    created_at timestamp with time zone DEFAULT now(),
    iccid text
);

-- 4. RESELLER NUMBERS TABLE (junction)
CREATE TABLE IF NOT EXISTS public.reseller_numbers (
    reseller_id bigint REFERENCES public.resellers(id),
    number_id bigint REFERENCES public.numbers(id),
    active boolean DEFAULT true,
    created_at timestamp with time zone DEFAULT now(),
    PRIMARY KEY (reseller_id, number_id)
);

-- 5. SIMS TABLE
CREATE TABLE IF NOT EXISTS public.sims (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    iccid text UNIQUE NOT NULL,
    port text,
    status text DEFAULT 'active' CHECK (status IN ('pending', 'provisioning', 'active', 'suspended', 'canceled', 'error')),
    created_at timestamp with time zone DEFAULT now(),
    mobility_subscription_id bigint,
    status_reason text,
    rotation_status text DEFAULT 'ready' CHECK (rotation_status IN ('ready', 'rotating', 'success', 'failed')),
    last_rotation_at timestamp with time zone,
    last_mdn_rotated_at timestamp with time zone,
    rotation_lock_until timestamp with time zone,
    last_rotation_error text,
    rotation_attempts integer DEFAULT 0
);

-- 6. SIM NUMBERS TABLE (phone number history)
CREATE TABLE IF NOT EXISTS public.sim_numbers (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sim_id bigint REFERENCES public.sims(id) NOT NULL,
    e164 text NOT NULL,
    valid_from timestamp with time zone DEFAULT now(),
    valid_to timestamp with time zone,
    verification_code text,
    verification_sent_at timestamp with time zone,
    verified_at timestamp with time zone,
    verification_status text DEFAULT 'pending'
);

-- 7. RESELLER SIMS TABLE (junction)
CREATE TABLE IF NOT EXISTS public.reseller_sims (
    reseller_id bigint REFERENCES public.resellers(id),
    sim_id bigint REFERENCES public.sims(id),
    active boolean DEFAULT true,
    created_at timestamp with time zone DEFAULT now(),
    last_number_online_sent_at timestamp with time zone,
    PRIMARY KEY (reseller_id, sim_id)
);

-- 8. RESELLER WEBHOOKS TABLE
CREATE TABLE IF NOT EXISTS public.reseller_webhooks (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reseller_id bigint REFERENCES public.resellers(id),
    url text NOT NULL,
    enabled boolean DEFAULT true,
    created_at timestamp with time zone DEFAULT now()
);

-- 9. INBOUND SMS TABLE
CREATE TABLE IF NOT EXISTS public.inbound_sms (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    to_number text NOT NULL,
    from_number text NOT NULL,
    body text NOT NULL,
    received_at timestamp with time zone NOT NULL,
    port text,
    raw jsonb,
    created_at timestamp with time zone DEFAULT now(),
    sim_id bigint REFERENCES public.sims(id),
    message_id text
);

-- 10. WEBHOOK DELIVERIES TABLE (deduplication)
CREATE TABLE IF NOT EXISTS public.webhook_deliveries (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    message_id text UNIQUE NOT NULL,
    event_type text NOT NULL,
    reseller_id bigint REFERENCES public.resellers(id),
    webhook_url text NOT NULL,
    payload jsonb NOT NULL,
    status text DEFAULT 'pending',
    attempts integer DEFAULT 0,
    last_attempt_at timestamp with time zone,
    delivered_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now()
);

-- 11. HELIX API LOGS TABLE
CREATE TABLE IF NOT EXISTS public.helix_api_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id text NOT NULL,
    step text NOT NULL,
    iccid text,
    imei text,
    request_url text NOT NULL,
    request_method text NOT NULL,
    request_headers jsonb,
    request_body jsonb,
    response_status integer,
    response_ok boolean,
    response_headers jsonb,
    response_body_text text,
    response_body_json jsonb,
    error text,
    created_at timestamp with time zone DEFAULT now()
);

-- 12. INDEXES FOR PERFORMANCE
CREATE INDEX IF NOT EXISTS idx_sims_iccid ON public.sims(iccid);
CREATE INDEX IF NOT EXISTS idx_sims_status ON public.sims(status);
CREATE INDEX IF NOT EXISTS idx_sim_numbers_sim_id ON public.sim_numbers(sim_id);
CREATE INDEX IF NOT EXISTS idx_sim_numbers_e164 ON public.sim_numbers(e164);
CREATE INDEX IF NOT EXISTS idx_sim_numbers_valid_to ON public.sim_numbers(valid_to);
CREATE INDEX IF NOT EXISTS idx_inbound_sms_sim_id ON public.inbound_sms(sim_id);
CREATE INDEX IF NOT EXISTS idx_inbound_sms_to_number ON public.inbound_sms(to_number);
CREATE INDEX IF NOT EXISTS idx_inbound_sms_received_at ON public.inbound_sms(received_at);
CREATE INDEX IF NOT EXISTS idx_inbound_sms_message_id ON public.inbound_sms(message_id);
CREATE INDEX IF NOT EXISTS idx_webhook_deliveries_message_id ON public.webhook_deliveries(message_id);
CREATE INDEX IF NOT EXISTS idx_helix_api_logs_run_id ON public.helix_api_logs(run_id);
CREATE INDEX IF NOT EXISTS idx_helix_api_logs_iccid ON public.helix_api_logs(iccid);

-- 13. GRANT PERMISSIONS (for Supabase)
GRANT ALL ON ALL TABLES IN SCHEMA public TO postgres, anon, authenticated, service_role;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO postgres, anon, authenticated, service_role;

-- ============================================
-- SCHEMA SETUP COMPLETE
-- ============================================
