-- captured from PROD 2026-09-23 (lzjqegxazqlktttyybth) with pg_attribute / pg_get_constraintdef /
-- pg_indexes. The table existed in PROD but no migration in this repo created it.
-- IF NOT EXISTS throughout: a no-op on PROD, builds the table on TEST or a rebuild.
-- bill_audit_uploads and bill_audit_lines share one file because lines has a
-- foreign key to uploads. The constraint names still carry the tables' old
-- wing_bill_* names; kept as PROD has them.

CREATE TABLE IF NOT EXISTS public.bill_audit_uploads (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  filename text,
  billing_period_start date,
  billing_period_end date,
  total_rows integer DEFAULT 0,
  total_amount numeric(10,2) DEFAULT 0,
  total_expected numeric(10,2) DEFAULT 0,
  discrepancy_count integer DEFAULT 0,
  overcharge_amount numeric(10,2) DEFAULT 0,
  status text DEFAULT 'pending'::text,
  error_message text,
  created_at timestamptz DEFAULT now(),
  vendor text NOT NULL DEFAULT 'wing'::text,
  invoice_no text,
  CONSTRAINT wing_bill_uploads_pkey PRIMARY KEY (id),
  CONSTRAINT wing_bill_uploads_status_check CHECK (status = ANY (ARRAY['pending'::text, 'processing'::text, 'complete'::text, 'error'::text]))
);

CREATE TABLE IF NOT EXISTS public.bill_audit_lines (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  upload_id bigint NOT NULL,
  wing_id text,
  item_type text,
  description text,
  from_date timestamptz,
  to_date timestamptz,
  subscription_name text,
  subscription_iccid text,
  subscription_identifier text,
  carrier text,
  price numeric(10,2),
  sim_id bigint,
  sim_status text,
  expected_price numeric(10,2),
  discrepancy_type text,
  discrepancy_detail text,
  created_at timestamptz DEFAULT now(),
  vendor text NOT NULL DEFAULT 'wing'::text,
  bypassed_plan_id text,
  CONSTRAINT wing_bill_lines_pkey PRIMARY KEY (id),
  CONSTRAINT wing_bill_lines_upload_id_fkey FOREIGN KEY (upload_id) REFERENCES public.bill_audit_uploads(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_bill_audit_lines_discrepancy ON public.bill_audit_lines USING btree (discrepancy_type) WHERE (discrepancy_type IS NOT NULL);
CREATE INDEX IF NOT EXISTS idx_bill_audit_lines_iccid ON public.bill_audit_lines USING btree (subscription_iccid);
CREATE INDEX IF NOT EXISTS idx_bill_audit_lines_plan_id ON public.bill_audit_lines USING btree (bypassed_plan_id);
CREATE INDEX IF NOT EXISTS idx_bill_audit_lines_upload_id ON public.bill_audit_lines USING btree (upload_id);

-- PROD: RLS on, no policies; only service_role holds grants.
ALTER TABLE public.bill_audit_uploads ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.bill_audit_uploads FROM anon, authenticated;
GRANT ALL ON public.bill_audit_uploads TO service_role;

-- PROD: RLS on, no policies; only service_role holds grants.
ALTER TABLE public.bill_audit_lines ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.bill_audit_lines FROM anon, authenticated;
GRANT ALL ON public.bill_audit_lines TO service_role;
