-- Audit log for manual field corrections made via the dashboard Sims editor.
-- Applied to the TEST project 2026-07-17; apply to PROD at Stage 2 rollout of the
-- sims-table redesign (see docs/superpowers/specs/2026-07-17-sims-table-redesign.md).
create table if not exists sim_edit_log (
  id bigint generated by default as identity primary key,
  sim_id bigint not null references sims(id) on delete cascade,
  field text not null,
  old_value text,
  new_value text,
  changed_by text not null default 'dashboard',
  source text not null default 'dashboard-ui',
  changed_at timestamptz not null default now()
);
create index if not exists sim_edit_log_sim_idx on sim_edit_log(sim_id, changed_at desc);
alter table sim_edit_log enable row level security;
