-- captured from PROD 2026-09-23 (lzjqegxazqlktttyybth) with pg_attribute / pg_get_constraintdef /
-- pg_indexes. The table existed in PROD but no migration in this repo created it.
-- IF NOT EXISTS throughout: a no-op on PROD, builds the table on TEST or a rebuild.
-- Note: PROD's imei_pool_status_check allows available / in_use / retired only.
-- agent/constraints.md section 7 also lists 'blocked'; PROD does not allow it.
-- Captured as PROD has it.

CREATE TABLE IF NOT EXISTS public.imei_pool (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  imei text NOT NULL,
  status text NOT NULL DEFAULT 'available'::text,
  sim_id bigint,
  assigned_at timestamptz,
  previous_sim_id bigint,
  notes text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  gateway_id integer,
  port text,
  slot integer,
  device_type text NOT NULL DEFAULT 'phone'::text,
  CONSTRAINT imei_pool_pkey PRIMARY KEY (id),
  CONSTRAINT imei_pool_imei_key UNIQUE (imei),
  CONSTRAINT imei_format_check CHECK ((length(imei) = 15) AND (imei ~ '^\d{15}$'::text)),
  CONSTRAINT imei_pool_device_type_check CHECK (device_type = ANY (ARRAY['phone'::text, 'router'::text])),
  CONSTRAINT imei_pool_status_check CHECK (status = ANY (ARRAY['available'::text, 'in_use'::text, 'retired'::text])),
  CONSTRAINT imei_pool_gateway_id_fkey FOREIGN KEY (gateway_id) REFERENCES public.gateways(id),
  CONSTRAINT imei_pool_sim_id_fkey FOREIGN KEY (sim_id) REFERENCES public.sims(id)
);

CREATE INDEX IF NOT EXISTS idx_imei_pool_sim_id ON public.imei_pool USING btree (sim_id);
CREATE INDEX IF NOT EXISTS idx_imei_pool_status ON public.imei_pool USING btree (status);
CREATE INDEX IF NOT EXISTS imei_pool_device_type_status_idx ON public.imei_pool USING btree (device_type, status);
CREATE UNIQUE INDEX IF NOT EXISTS imei_pool_unique_in_use_sim ON public.imei_pool USING btree (sim_id) WHERE ((status = 'in_use'::text) AND (sim_id IS NOT NULL));
CREATE UNIQUE INDEX IF NOT EXISTS imei_pool_unique_in_use_slot ON public.imei_pool USING btree (gateway_id, port) WHERE ((status = 'in_use'::text) AND (gateway_id IS NOT NULL) AND (port IS NOT NULL));

-- PROD: RLS on, no policies; only service_role holds grants.
ALTER TABLE public.imei_pool ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.imei_pool FROM anon, authenticated;
GRANT ALL ON public.imei_pool TO service_role;
